branch-defaults:
  master:
    environment: timepredictor-dev-test
global:
  application_name: timePredictor-dev
  default_ec2_keyname: null
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-east-1
  profile: eb-cli
  sc: git
