branch-defaults:
  master:
    environment: timePredictor-dev
    group_suffix: null
global:
  application_name: timePredictor
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-east-1
  profile: eb-cli
  sc: git
